### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kholbekj** [bensinc/rubymush#1]
Could you please specify a license for this project? Would love to play around with it, but without a license I don't feel like spending time. 

Looks like a cool project!

**Comment by bensinc** [comment]
I just put it under the MIT license.

I haven't done much with this project in a while, but I have an instance running here: bensinclair.com 8081

It could use some work to make it really functional!

Thanks!

**Comment by kholbekj** [comment]
Perfect, thanks for the quick reply!
